### ISSUE TITLE
yahooanswers2 warrior project failing when previously was working - other projects working still

### ISSUE THREAD

**Issue by restlessmonkey** [ArchiveTeam/yahooanswers-grab#5]
Not sure who to ask. Sorry if this is the wrong place. 
I installed the warrior docker on my synology NAS to help the yahooanswers2 project. Was working find but stopped working with the following error. I've re-created the docker, changes projects, etc but no luck, even when other projects load fine and work.

2021-04-10 23:13:44,658 - seesaw.warrior - DEBUG - Start selected project yahooanswers2 (reinstall=False)
2021-04-10 23:13:44,659 - seesaw.warrior - DEBUG - Check project has update yahooanswers2
2021-04-10 23:13:44,777 - seesaw.warrior - DEBUG - git fetch
2021-04-10 23:13:45,148 - seesaw.warrior - DEBUG - False
2021-04-10 23:13:45,149 - seesaw.warrior - DEBUG - Clone project yahooanswers2 /home/warrior/projects/yahooanswers2
2021-04-10 23:13:45,156 - seesaw.warrior - DEBUG - Cloning version 180e4b5
2021-04-10 23:13:45,157 - seesaw.warrior - DEBUG - Load pipeline /home/warrior/data/projects/yahooanswers2-180e4b5/pipeline.py
2021-04-10 23:13:45,158 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
2021-04-10 23:13:45,158 - seesaw.warrior - DEBUG - Executing pipeline
2021-04-10 23:13:45,180 - seesaw.warrior - ERROR - Error loading pipeline
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 736, in start_selected_project
    (project, pipeline, config_values) = self.load_pipeline(
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 686, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 54, in <module>
Exception: No usable Wget+At found.
2021-04-10 23:13:45,181 - seesaw.warrior - WARNING - Project yahooanswers2 did not install correctly and we're ignoring this problem.

**Comment by dyc3** [comment]
How are you running warrior? Are you using the VM, the docker image, or something else?

**Comment by restlessmonkey** [comment]
Hi - Docker image/latest.  Here's more log that might help.

2021-04-11 00:06:46,180 - seesaw.warrior - DEBUG - Select project yahooanswers2
2021-04-11 00:06:46,183 - seesaw.warrior - DEBUG - Start selected project yahooanswers2 (reinstall=False)
2021-04-11 00:06:46,183 - seesaw.warrior - DEBUG - Check project has update yahooanswers2
2021-04-11 00:06:46,194 - seesaw.warrior - DEBUG - git fetch
2021-04-11 00:06:46,595 - seesaw.warrior - DEBUG - False
2021-04-11 00:06:46,597 - seesaw.warrior - DEBUG - Clone project yahooanswers2 /home/warrior/projects/yahooanswers2
2021-04-11 00:06:46,604 - seesaw.warrior - DEBUG - Cloning version 180e4b5
2021-04-11 00:06:46,605 - seesaw.warrior - DEBUG - Load pipeline /home/warrior/data/projects/yahooanswers2-180e4b5/pipeline.py
2021-04-11 00:06:46,606 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
2021-04-11 00:06:46,607 - seesaw.warrior - DEBUG - Executing pipeline
Looking for Wget+AT in ./wget-at
./wget-at: [Errno 2] No such file or directory: './wget-at'
Looking for Wget+AT in /home/warrior/data/wget-at
/home/warrior/data/wget-at: Incorrect Wget+AT version (want ['GNU Wget 1.20.3-at.20210410.01']).
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 736, in start_selected_project
    (project, pipeline, config_values) = self.load_pipeline(
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 686, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 54, in <module>
Exception: No usable Wget+At found.
2021-04-11 00:06:46,716 - seesaw.warrior - WARNING - Project yahooanswers2 did not install correctly and we're ignoring this problem.

**Comment by dyc3** [comment]
Seems pretty weird. I'll relay this to the IRC chat

**Comment by restlessmonkey** [comment]
Here it is properly selecting the reddit project: 

2021-04-11 00:33:12,770 - seesaw.warrior - DEBUG - Select project reddit
2021-04-11 00:33:12,772 - seesaw.warrior - DEBUG - Start selected project reddit (reinstall=False)
2021-04-11 00:33:12,772 - seesaw.warrior - DEBUG - Check project has update reddit
2021-04-11 00:33:12,779 - seesaw.warrior - DEBUG - git fetch
2021-04-11 00:33:13,168 - seesaw.warrior - DEBUG - False
2021-04-11 00:33:13,170 - seesaw.warrior - DEBUG - Clone project reddit /home/warrior/projects/reddit
2021-04-11 00:33:13,177 - seesaw.warrior - DEBUG - Cloning version 1f9e995
2021-04-11 00:33:13,178 - seesaw.warrior - DEBUG - Load pipeline /home/warrior/data/projects/reddit-1f9e995/pipeline.py
2021-04-11 00:33:13,179 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
2021-04-11 00:33:13,179 - seesaw.warrior - DEBUG - Executing pipeline
Looking for Wget+AT in ./wget-at
./wget-at: [Errno 2] No such file or directory: './wget-at'
Looking for Wget+AT in /home/warrior/data/wget-at-gnutls
Found usable Wget+AT in /home/warrior/data/wget-at-gnutls
2021-04-11 00:33:13,203 - seesaw.warrior - DEBUG - Stopped ConfigValue collecting
2021-04-11 00:33:13,206 - seesaw.warrior - INFO - Project reddit installed
Downloading latest dictionary.
2021-04-11 00:33:15,437 - seesaw.warrior - DEBUG - Select project auto
2021-04-11 00:33:15,437 - seesaw.warrior - DEBUG - Update warrior hq.
2021-04-11 00:33:15,438 - seesaw.warrior - DEBUG - Warrior ID ''.
2021-04-11 00:33:16,092 - seesaw.warrior - DEBUG - Select project reddit

/swapped two words for grammar

**Comment by dylan-park** [comment]
> Not sure who to ask. Sorry if this is the wrong place. 
> I installed the warrior docker on my synology NAS to help the yahooanswers2 project. Was working find but stopped working with the following error. I've re-created the docker, changes projects, etc but no luck, even when other projects load fine and work.
> 
> 2021-04-10 23:13:44,658 - seesaw.warrior - DEBUG - Start selected project yahooanswers2 (reinstall=False)
> 2021-04-10 23:13:44,659 - seesaw.warrior - DEBUG - Check project has update yahooanswers2
> 2021-04-10 23:13:44,777 - seesaw.warrior - DEBUG - git fetch
> 2021-04-10 23:13:45,148 - seesaw.warrior - DEBUG - False
> 2021-04-10 23:13:45,149 - seesaw.warrior - DEBUG - Clone project yahooanswers2 /home/warrior/projects/yahooanswers2
> 2021-04-10 23:13:45,156 - seesaw.warrior - DEBUG - Cloning version 180e4b5
> 2021-04-10 23:13:45,157 - seesaw.warrior - DEBUG - Load pipeline /home/warrior/data/projects/yahooanswers2-180e4b5/pipeline.py
> 2021-04-10 23:13:45,158 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
> 2021-04-10 23:13:45,158 - seesaw.warrior - DEBUG - Executing pipeline
> 2021-04-10 23:13:45,180 - seesaw.warrior - ERROR - Error loading pipeline
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 736, in start_selected_project
>     (project, pipeline, config_values) = self.load_pipeline(
>   File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 686, in load_pipeline
>     exec(pipeline_str, local_context, global_context)
>   File "<string>", line 54, in <module>
> Exception: No usable Wget+At found.
> 2021-04-10 23:13:45,181 - seesaw.warrior - WARNING - Project yahooanswers2 did not install correctly and we're ignoring this problem.

When this was happening to me this morning, completely removing both the warrior image, as well as the watchtower image and redownload them seemed to solve the issue for me.

**Comment by restlessmonkey** [comment]
> > Not sure who to ask. Sorry if this is the wrong place.
> > I installed the warrior docker on my synology NAS to help the yahooanswers2 project. Was working find but stopped working with the following error. I've re-created the docker, changes projects, etc but no luck, even when other projects load fine and work.
> > 2021-04-10 23:13:44,658 - seesaw.warrior - DEBUG - Start selected project yahooanswers2 (reinstall=False)
> > 2021-04-10 23:13:44,659 - seesaw.warrior - DEBUG - Check project has update yahooanswers2
> > 2021-04-10 23:13:44,777 - seesaw.warrior - DEBUG - git fetch
> > 2021-04-10 23:13:45,148 - seesaw.warrior - DEBUG - False
> > 2021-04-10 23:13:45,149 - seesaw.warrior - DEBUG - Clone project yahooanswers2 /home/warrior/projects/yahooanswers2
> > 2021-04-10 23:13:45,156 - seesaw.warrior - DEBUG - Cloning version [180e4b5](https://github.com/ArchiveTeam/yahooanswers-grab/commit/180e4b55fabcb73b39e61f629e80a35c1b454457)
> > 2021-04-10 23:13:45,157 - seesaw.warrior - DEBUG - Load pipeline /home/warrior/data/projects/yahooanswers2-180e4b5/pipeline.py
> > 2021-04-10 23:13:45,158 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
> > 2021-04-10 23:13:45,158 - seesaw.warrior - DEBUG - Executing pipeline
> > 2021-04-10 23:13:45,180 - seesaw.warrior - ERROR - Error loading pipeline
> > Traceback (most recent call last):
> > File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 736, in start_selected_project
> > (project, pipeline, config_values) = self.load_pipeline(
> > File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 686, in load_pipeline
> > exec(pipeline_str, local_context, global_context)
> > File "", line 54, in 
> > Exception: No usable Wget+At found.
> > 2021-04-10 23:13:45,181 - seesaw.warrior - WARNING - Project yahooanswers2 did not install correctly and we're ignoring this problem.
> 
> When this was happening to me this morning, completely removing both the warrior image, as well as the watchtower image and redownload them seemed to solve the issue for me.

Thanks. I'll try that now.  Didn't want to take the nuclear option in case something needed to be fixed :-)

**Comment by restlessmonkey** [comment]
No luck....new log. I'm open to suggestions.

2021-04-11 02:19:15,262 - seesaw.warrior - DEBUG - Update warrior hq.
2021-04-11 02:19:15,262 - seesaw.warrior - DEBUG - Warrior ID ''.
2021-04-11 02:19:33,816 - seesaw.warrior - DEBUG - Select project yahooanswers2
2021-04-11 02:19:33,818 - seesaw.warrior - DEBUG - Start selected project yahooanswers2 (reinstall=False)
2021-04-11 02:19:33,818 - seesaw.warrior - DEBUG - Install project yahooanswers2
2021-04-11 02:19:33,820 - seesaw.warrior - DEBUG - git clone
2021-04-11 02:19:36,992 - seesaw.warrior - DEBUG - git operation: Cloning into '/home/warrior/projects/yahooanswers2'...

2021-04-11 02:19:36,993 - seesaw.warrior - DEBUG - Install complete Cloning into '/home/warrior/projects/yahooanswers2'...

2021-04-11 02:19:36,994 - seesaw.warrior - DEBUG - Result of the install process: True
2021-04-11 02:19:36,995 - seesaw.warrior - DEBUG - Clone project yahooanswers2 /home/warrior/projects/yahooanswers2
2021-04-11 02:19:37,001 - seesaw.warrior - DEBUG - Cloning version 180e4b5
2021-04-11 02:19:37,099 - seesaw.warrior - DEBUG - Load pipeline /home/warrior/data/projects/yahooanswers2-180e4b5/pipeline.py
2021-04-11 02:19:37,100 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
2021-04-11 02:19:37,100 - seesaw.warrior - DEBUG - Executing pipeline
2021-04-11 02:19:39,083 - seesaw.warrior - ERROR - Error loading pipeline
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 736, in start_selected_project
    (project, pipeline, config_values) = self.load_pipeline(
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 686, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 54, in <module>
Exception: No usable Wget+At found.
2021-04-11 02:19:39,112 - seesaw.warrior - WARNING - Project yahooanswers2 did not install correctly and we're ignoring this problem.

**Comment by restlessmonkey** [comment]
So it looks like only 3 of the projects listed are actually working for me.  This shows more of the failing ones.
The only projects that appear to be working are reddit, urlteam, and 'archiveteamschoice' which selected reddit, apparently.

2021-04-11 02:36:18,391 - seesaw.warrior - DEBUG - Update warrior hq.
2021-04-11 02:36:18,391 - seesaw.warrior - DEBUG - Warrior ID ''.
2021-04-11 02:37:21,862 - seesaw.warrior - DEBUG - Select project yahooanswers2
2021-04-11 02:37:21,864 - seesaw.warrior - DEBUG - Start selected project yahooanswers2 (reinstall=False)
2021-04-11 02:37:21,865 - seesaw.warrior - DEBUG - Install project yahooanswers2
2021-04-11 02:37:21,866 - seesaw.warrior - DEBUG - git clone
2021-04-11 02:37:23,272 - seesaw.warrior - DEBUG - git operation: Cloning into '/home/warrior/projects/yahooanswers2'...

2021-04-11 02:37:23,273 - seesaw.warrior - DEBUG - Install complete Cloning into '/home/warrior/projects/yahooanswers2'...

2021-04-11 02:37:23,274 - seesaw.warrior - DEBUG - Result of the install process: True
2021-04-11 02:37:23,275 - seesaw.warrior - DEBUG - Clone project yahooanswers2 /home/warrior/projects/yahooanswers2
2021-04-11 02:37:23,282 - seesaw.warrior - DEBUG - Cloning version 180e4b5
2021-04-11 02:37:23,444 - seesaw.warrior - DEBUG - Load pipeline /home/warrior/data/projects/yahooanswers2-180e4b5/pipeline.py
2021-04-11 02:37:23,445 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
2021-04-11 02:37:23,446 - seesaw.warrior - DEBUG - Executing pipeline
2021-04-11 02:37:24,518 - seesaw.warrior - ERROR - Error loading pipeline
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 736, in start_selected_project
    (project, pipeline, config_values) = self.load_pipeline(
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 686, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 54, in <module>
Exception: No usable Wget+At found.
2021-04-11 02:37:24,525 - seesaw.warrior - WARNING - Project yahooanswers2 did not install correctly and we're ignoring this problem.
2021-04-11 02:37:33,453 - seesaw.warrior - DEBUG - Select project webs
2021-04-11 02:37:33,454 - seesaw.warrior - DEBUG - Start selected project webs (reinstall=False)
2021-04-11 02:37:33,455 - seesaw.warrior - DEBUG - Install project webs
2021-04-11 02:37:33,458 - seesaw.warrior - DEBUG - git clone
2021-04-11 02:37:34,611 - seesaw.warrior - DEBUG - git operation: Cloning into '/home/warrior/projects/webs'...

2021-04-11 02:37:34,613 - seesaw.warrior - DEBUG - Install complete Cloning into '/home/warrior/projects/webs'...

2021-04-11 02:37:34,614 - seesaw.warrior - DEBUG - Result of the install process: True
2021-04-11 02:37:34,615 - seesaw.warrior - DEBUG - Clone project webs /home/warrior/projects/webs
2021-04-11 02:37:34,623 - seesaw.warrior - DEBUG - Cloning version fa3a3ec
2021-04-11 02:37:34,651 - seesaw.warrior - DEBUG - Load pipeline /home/warrior/data/projects/webs-fa3a3ec/pipeline.py
2021-04-11 02:37:34,651 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
2021-04-11 02:37:34,652 - seesaw.warrior - DEBUG - Executing pipeline
2021-04-11 02:37:34,674 - seesaw.warrior - ERROR - Error loading pipeline
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 736, in start_selected_project
    (project, pipeline, config_values) = self.load_pipeline(
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 686, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 47, in <module>
Exception: No usable Wget+At found.
2021-04-11 02:37:34,675 - seesaw.warrior - WARNING - Project webs did not install correctly and we're ignoring this problem.
2021-04-11 02:37:44,610 - seesaw.warrior - DEBUG - Select project periscope
2021-04-11 02:37:44,612 - seesaw.warrior - DEBUG - Start selected project periscope (reinstall=False)
2021-04-11 02:37:44,612 - seesaw.warrior - DEBUG - Install project periscope
2021-04-11 02:37:44,613 - seesaw.warrior - DEBUG - git clone
2021-04-11 02:37:45,213 - seesaw.warrior - DEBUG - git operation: Cloning into '/home/warrior/projects/periscope'...

2021-04-11 02:37:45,215 - seesaw.warrior - DEBUG - Install complete Cloning into '/home/warrior/projects/periscope'...

2021-04-11 02:37:45,217 - seesaw.warrior - DEBUG - Result of the install process: True
2021-04-11 02:37:45,218 - seesaw.warrior - DEBUG - Clone project periscope /home/warrior/projects/periscope
2021-04-11 02:37:45,227 - seesaw.warrior - DEBUG - Cloning version 0090193
2021-04-11 02:37:45,269 - seesaw.warrior - DEBUG - Load pipeline /home/warrior/data/projects/periscope-0090193/pipeline.py
2021-04-11 02:37:45,270 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
2021-04-11 02:37:45,271 - seesaw.warrior - DEBUG - Executing pipeline
2021-04-11 02:37:45,293 - seesaw.warrior - ERROR - Error loading pipeline
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 736, in start_selected_project
    (project, pipeline, config_values) = self.load_pipeline(
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 686, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 47, in <module>
Exception: No usable Wget+At found.
2021-04-11 02:37:45,295 - seesaw.warrior - WARNING - Project periscope did not install correctly and we're ignoring this problem.
2021-04-11 02:38:01,570 - seesaw.warrior - DEBUG - Select project githubtest2
2021-04-11 02:38:01,572 - seesaw.warrior - DEBUG - Start selected project githubtest2 (reinstall=False)
2021-04-11 02:38:01,572 - seesaw.warrior - DEBUG - Install project githubtest2
2021-04-11 02:38:01,573 - seesaw.warrior - DEBUG - git clone
2021-04-11 02:38:03,282 - seesaw.warrior - DEBUG - git operation: Cloning into '/home/warrior/projects/githubtest2'...

2021-04-11 02:38:03,287 - seesaw.warrior - DEBUG - Install complete Cloning into '/home/warrior/projects/githubtest2'...

2021-04-11 02:38:03,289 - seesaw.warrior - DEBUG - Result of the install process: True
2021-04-11 02:38:03,290 - seesaw.warrior - DEBUG - Clone project githubtest2 /home/warrior/projects/githubtest2
2021-04-11 02:38:03,301 - seesaw.warrior - DEBUG - Cloning version 75464a6
2021-04-11 02:38:03,334 - seesaw.warrior - DEBUG - Load pipeline /home/warrior/data/projects/githubtest2-75464a6/pipeline.py
2021-04-11 02:38:03,335 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
2021-04-11 02:38:03,335 - seesaw.warrior - DEBUG - Executing pipeline
2021-04-11 02:38:03,357 - seesaw.warrior - ERROR - Error loading pipeline
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 736, in start_selected_project
    (project, pipeline, config_values) = self.load_pipeline(
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 686, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 51, in <module>
Exception: No usable Wget+At found.
2021-04-11 02:38:03,359 - seesaw.warrior - WARNING - Project githubtest2 did not install correctly and we're ignoring this problem.
2021-04-11 02:38:18,779 - seesaw.warrior - DEBUG - Select project mediafire
2021-04-11 02:38:18,781 - seesaw.warrior - DEBUG - Start selected project mediafire (reinstall=False)
2021-04-11 02:38:18,781 - seesaw.warrior - DEBUG - Install project mediafire
2021-04-11 02:38:18,783 - seesaw.warrior - DEBUG - git clone
2021-04-11 02:38:19,386 - seesaw.warrior - DEBUG - git operation: Cloning into '/home/warrior/projects/mediafire'...

2021-04-11 02:38:19,388 - seesaw.warrior - DEBUG - Install complete Cloning into '/home/warrior/projects/mediafire'...

2021-04-11 02:38:19,389 - seesaw.warrior - DEBUG - Result of the install process: True
2021-04-11 02:38:19,390 - seesaw.warrior - DEBUG - Clone project mediafire /home/warrior/projects/mediafire
2021-04-11 02:38:19,398 - seesaw.warrior - DEBUG - Cloning version 3fc217a
2021-04-11 02:38:19,436 - seesaw.warrior - DEBUG - Load pipeline /home/warrior/data/projects/mediafire-3fc217a/pipeline.py
2021-04-11 02:38:19,437 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
2021-04-11 02:38:19,437 - seesaw.warrior - DEBUG - Executing pipeline
2021-04-11 02:38:19,458 - seesaw.warrior - ERROR - Error loading pipeline
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 736, in start_selected_project
    (project, pipeline, config_values) = self.load_pipeline(
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 686, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 47, in <module>
Exception: No usable Wget+At found.
2021-04-11 02:38:19,459 - seesaw.warrior - WARNING - Project mediafire did not install correctly and we're ignoring this problem.
2021-04-11 02:38:30,252 - seesaw.warrior - DEBUG - Select project google-sites
2021-04-11 02:38:30,254 - seesaw.warrior - DEBUG - Start selected project google-sites (reinstall=False)
2021-04-11 02:38:30,256 - seesaw.warrior - DEBUG - Install project google-sites
2021-04-11 02:38:30,260 - seesaw.warrior - DEBUG - git clone
2021-04-11 02:38:32,787 - seesaw.warrior - DEBUG - git operation: Cloning into '/home/warrior/projects/google-sites'...

2021-04-11 02:38:32,789 - seesaw.warrior - DEBUG - Install complete Cloning into '/home/warrior/projects/google-sites'...

2021-04-11 02:38:32,790 - seesaw.warrior - DEBUG - Result of the install process: True
2021-04-11 02:38:32,791 - seesaw.warrior - DEBUG - Clone project google-sites /home/warrior/projects/google-sites
2021-04-11 02:38:32,799 - seesaw.warrior - DEBUG - Cloning version 36b8de7
2021-04-11 02:38:32,826 - seesaw.warrior - DEBUG - Load pipeline /home/warrior/data/projects/google-sites-36b8de7/pipeline.py
2021-04-11 02:38:32,827 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
2021-04-11 02:38:32,827 - seesaw.warrior - DEBUG - Executing pipeline
2021-04-11 02:38:32,848 - seesaw.warrior - ERROR - Error loading pipeline
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 736, in start_selected_project
    (project, pipeline, config_values) = self.load_pipeline(
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 686, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 50, in <module>
Exception: No usable Wget+At found.
2021-04-11 02:38:32,849 - seesaw.warrior - WARNING - Project google-sites did not install correctly and we're ignoring this problem.
2021-04-11 02:38:52,208 - seesaw.warrior - DEBUG - Select project auto
2021-04-11 02:38:52,209 - seesaw.warrior - DEBUG - Update warrior hq.
2021-04-11 02:38:52,210 - seesaw.warrior - DEBUG - Warrior ID ''.
2021-04-11 02:38:52,937 - seesaw.warrior - DEBUG - Select project reddit
2021-04-11 02:38:52,938 - seesaw.warrior - DEBUG - Start selected project reddit (reinstall=False)
2021-04-11 02:38:52,939 - seesaw.warrior - DEBUG - Install project reddit
2021-04-11 02:38:52,940 - seesaw.warrior - DEBUG - git clone
2021-04-11 02:38:54,422 - seesaw.warrior - DEBUG - git operation: Cloning into '/home/warrior/projects/reddit'...

2021-04-11 02:38:54,427 - seesaw.warrior - DEBUG - Install complete Cloning into '/home/warrior/projects/reddit'...

2021-04-11 02:38:54,430 - seesaw.warrior - DEBUG - Result of the install process: True
2021-04-11 02:38:54,432 - seesaw.warrior - DEBUG - Clone project reddit /home/warrior/projects/reddit
2021-04-11 02:38:54,453 - seesaw.warrior - DEBUG - Cloning version 1f9e995
2021-04-11 02:38:54,608 - seesaw.warrior - DEBUG - Load pipeline /home/warrior/data/projects/reddit-1f9e995/pipeline.py
2021-04-11 02:38:54,611 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
2021-04-11 02:38:54,618 - seesaw.warrior - DEBUG - Executing pipeline
2021-04-11 02:38:54,841 - seesaw.warrior - DEBUG - Stopped ConfigValue collecting
2021-04-11 02:38:54,847 - seesaw.warrior - INFO - Project reddit installed

**Comment by TomGlass** [comment]
Using dockerhub image which is outdated please use atdr.meo.ws/archiveteam/warrior-dockerfile

**Comment by restlessmonkey** [comment]
FYI - looks like the docker hub image was pending an update. It has been updated and the error no longer appears.
Thanks!
